// this file is generated by compiler
global["$$_SUMMER_ENV"] = "test";
import summermysql from '@summer/mysql';
global["$$_PLUGINS"] = [summermysql];
import * as envConfig from "./config/test.config";
global["$$_ENV_CONFIG"] = envConfig;
import * as $M0 from './controllers/ControllerParamController';
import * as $M1 from './controllers/HelloController';
import * as $M2 from './controllers/PersonController';
import * as $M3 from './middleware/PathMiddleware';
$M0;$M1;$M2;$M3;
import { Person } from './entity/person';
global["$$_ENTITIES"] = [Person];