// this file is generated by compiler
global["$$_SUMMER_ENV"] = "local";import * as envConfig from "./config/local.config";
global["$$_ENV_CONFIG"] = envConfig;
import * as $M0 from './controllers/ControllerParamController';
import * as $M1 from './controllers/HelloController';
import * as $M2 from './controllers/HelloEntry';
import * as $M3 from './controllers/PersonController';
import * as $M4 from './middleware/PathMiddleware';
$M0;
$M1;
$M2;
$M3;
$M4;
import { Person } from './entity/person';
global["$$_ENTITIES"] = [Person];