// this file is generated by compiler
process.env.SUMMER_ENV = "local"
import * as defaultConfig from "./config/default.config"
global["$$_DEFAULT_CONFIG"] = defaultConfig
import * as envConfig from "./config/local.config";
global["$$_ENV_CONFIG"] = envConfig
import '@summer-js/swagger'
import '@summer-js/typeorm'
import './controllers/AnimalController'
import './controllers/BookController'
import './controllers/ConfigController'
import './controllers/ControllerParamController'
import './controllers/ExampleController'
import './controllers/HelloController'
import './controllers/LoggerController'
import './controllers/MovieController'
import './controllers/PersonController'
import './controllers/SessionController'
import './controllers/SwaggerController'
import './controllers/TodoController'
import './decorators/index'

import './entity/person'
import './entity/todo'

