// this file is generated by compiler
global["$$_SUMMER_ENV"] = "prod";
import summerjstypeorm from '@summer-js/typeorm';
import summerjsswagger from '@summer-js/swagger';
global["$$_PLUGINS"] = [summerjstypeorm,summerjsswagger];
import * as defaultConfig from "./config/default.config";
global["$$_DEFAULT_CONFIG"] = defaultConfig;
import * as envConfig from "./config/prod.config";
global["$$_ENV_CONFIG"] = envConfig;
import * as $M0 from './controllers/AnimalController';
import * as $M1 from './controllers/BookController';
import * as $M2 from './controllers/ConfigController';
import * as $M3 from './controllers/ControllerParamController';
import * as $M4 from './controllers/ExampleController';
import * as $M5 from './controllers/HelloController';
import * as $M6 from './controllers/LoggerController';
import * as $M7 from './controllers/MovieController';
import * as $M8 from './controllers/SessionController';
import * as $M9 from './controllers/SwaggerController';
import * as $M10 from './decorators/index';
$M0;$M1;$M2;$M3;$M4;$M5;$M6;$M7;$M8;$M9;$M10;
import { Person } from './entity/person';
import { Todo } from './entity/todo';
global["$$_ENTITIES"] = [Person,Todo];
import { SummerSwaggerUIController } from "@summer-js/swagger";
SummerSwaggerUIController;

