// this file is generated by compiler
process.env.SUMMER_ENV = "test"
import * as defaultConfig from "./config/default.config"
global["$$_DEFAULT_CONFIG"] = defaultConfig
import * as envConfig from "./config/test.config";
global["$$_ENV_CONFIG"] = envConfig
import '@summer-js/typeorm'
import './controllers/AnimalController'
import './controllers/BookController'
import './controllers/ConfigController'
import './controllers/CookieController'
import './controllers/ExampleController'
import './controllers/HelloController'
import './controllers/LoggerController'
import './controllers/MovieController'
import './controllers/SessionController'
import './controllers/SwaggerController'
import './decorators/index'
import './entity/person'
import './entity/todo'
import './middleware/PathMiddleware'
import './migrations/1650585292097-migration'
import './with-db/PersonController'
import './with-db/TodoController'
import './test/controller/BasePathController'
import './test/controller/BuildInDecoratorTestController'
import './test/controller/CookieTestController'
import './test/controller/CorsTestController'
import './test/controller/ParamsValidationController'
import './test/controller/PathTestMiddleware'
