// this file is generated by compiler
process.env.SUMMER_ENV = "local"
import * as defaultConfig from "./config/default.config"
global["$$_DEFAULT_CONFIG"] = defaultConfig
import './controllers/HelloController'

